effortlesshome_security:
  #noonlight:
  rest_command:

# get customer name, phone number
    #https://devcust.effortlesshome.co/getcustomer/{{ customer_id }}   !secret eh_customer_id
    get_customer_info:
      url: "https://devcust.effortlesshome.co/getcustomerbyid/0"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
        eh_customer_id: !secret eh_customer_id
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true

# get address json, alarm pin
#https://devcust.effortlesshome.co/getsystembysystemid/{{ system_id }}   !secret eh_system_id
    get_system_info:
      url: "https://devcust.effortlesshome.co/getsystembysystemid/0"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true

    create_alarm:
      url: "https://dev.effortlesshome.co/createalarm/0"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
#      payload: '{"location":{"address":{"state":"{{ home_address_state }}","line1":"{{ home_address_line1 }}","line2":"{{ home_address_line2 }}","city":"{{ home_address_city }}","zip":"{{ home_address_zipcode }}"}},"services":{"police":true},"name":"{{ customer_name }}","phone":"{{ customer_phone }}","pin":"{{ alarm_pin }}"}'
      payload: '{"location":{{ address_json }},"services":{"police":true},"name":"{{ customer_name }}","phone":"{{ customer_phone }}","pin":"{{ alarm_pin }}"}'
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true

    save_alarm_record:
      url: "https://dev.effortlesshome.co/savealarmrecord/{{ alarm_id}}"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      verify_ssl: true

    update_alarm:
      url: "https://dev.effortlesshome.co/updatealarm/{{ alarm_id }}"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      payload: '{"status":"{{ status }}","pin":"{{ pin }}"}'
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true

    get_alarm_status:
      url: "https://dev.effortlesshome.co/getalarmstatus/{{ alarm_id }}"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true

    alarm_create_smoke_event:
      url: "https://dev.effortlesshome.co/createevents/{{ alarm_id }}"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      payload: '{"event_type":"alarm.device.activated_alarm","meta":{"attribute":"smoke","value":"detected","device_id":"{{ device_id }}","device_model":"{{ device_model }}","device_name":"{{ device_name }}","device_manufacturer":"{{ device_manufacturer }}"},"event_time":"{{ event_time }}"}'
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true

    alarm_create_lock_event:
      url: "https://dev.effortlesshome.co/createevents/{{ alarm_id }}"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      payload: '{"event_type":"alarm.device.value_changed","meta":{"attribute":"lock","value":"unlocked","device_id":"{{ device_id }}","device_model":"{{ device_model }}","device_name":"{{ device_name }}","device_manufacturer":"{{ device_manufacturer }}"},"event_time":"{{ event_time }}"}'
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true

    alarm_create_contactsensor_event:
      url: "https://dev.effortlesshome.co/createevents/{{ alarm_id }}"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      payload: '{"event_type":"alarm.device.value_changed","meta":{"attribute":"contact","value":"open","device_id":"{{ device_id }}","device_model":"{{ device_model }}","device_name":"{{ device_name }}","device_manufacturer":"{{ device_manufacturer }}"},"event_time":"{{ event_time }}"}'
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true

    alarm_create_motion_event:
      url: "https://dev.effortlesshome.co/createevents/{{ alarm_id }}"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      payload: '{event_type":"alarm.device.value_changed","meta":{"attribute":"motion","value":"detected","device_id":"{{ device_id }}","device_model":"{{ device_model }}","device_name":"{{ device_name }}","device_manufacturer":"{{ device_manufacturer }}"},"event_time":"{{ event_time }}"}'
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true

    alarm_create_freeze_event:
      url: "https://dev.effortlesshome.co/createevents/{{ alarm_id }}"
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      payload: '{"event_type":"alarm.device.value_changed","meta":{"attribute":"freeze","value":"detected","device_id":"{{ device_id }}","device_model":"{{ device_model }}","device_name":"{{ device_name }}","device_manufacturer":"{{ device_manufacturer }}"},"event_time":"{{ event_time }}"}'
      content_type:  'application/json; charset=utf-8'
      verify_ssl: true
 
  binary_sensor:
    - platform: rest
      resource: 'https://dev.effortlesshome.co/getalarmstatus/{{ alarm_id }}'
      method: POST
      headers:
        accept: "application/json, text/html"
        X-Custom-PSK: !secret security_monitoring_secret
        eh_system_id: !secret eh_system_id
      payload: '{"alarm_id":"{{ alarm_id }}"}'
      verify_ssl: true
      name: "getalarmstatus_sensor"
      unique_id: getalarmstatus_sensor
      value_template: '{{ value_json.content }}'

# Automations
#------------------------------------------------------------------------------
#  automation:

  # Scripts
#------------------------------------------------------------------------------
#  script:
